---
ci:
  autoupdate_schedule: quarterly
  skip: [render-teasers]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(feed\.json|_data/teasers\.json|assets/images/teasers/teasers-manifest\.json)$
      - id: check-yaml
      - id: check-json
        exclude: ^(feed\.json|_data/teasers\.json)$
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: pretty-format-json
        exclude: ^(feed\.json|_data/teasers\.json|package-lock\.json|package\.json|assets/images/teasers/teasers-manifest\.json)$
        args: ["--autofix"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks-system
        pass_filenames: false
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Shell script lint (shellcheck)
        files: ^scripts/.*\.sh$
        types: [file]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words=.codespell-ignore-words.txt", "--quiet-level=2"]
        exclude: ^(_site/|vendor/|node_modules/|.*\.lock|.*\.svg|.*\.webp)
  - repo: local
    hooks:
      - id: render-teasers
        always_run: true
        entry: npm run --silent render:teasers
        language: system
        name: Render teaser images
        pass_filenames: false
        stages: [pre-commit]
      - id: render-og
        always_run: true
        entry: npm run --silent render:og
        language: system
        name: Render og images
        pass_filenames: false
        stages: [pre-commit]
      - id: front-matter-validate
        name: Front matter validation
        entry: python scripts/validate_front_matter.py
        language: python
        types: [file]
        files: ^(_posts/.*\.md|_pages/.*\.md)$
        additional_dependencies: [pyyaml]
