title: Trevor Lauder
subtitle: Version 2.0
name: Trevor Lauder
title_separator: "—"
description: DevOps and SRE topics—automation, monitoring, tooling—plus a personal mix of coding projects, photography, and astrophotography.
minimal_mistakes_skin: custom
search: true
favicon: /assets/images/favicon.ico
url: https://trevorlauder.dev
baseurl: /
repository: trevorlauder/trevorlauder.dev
og_image: /assets/images/og.webp
teaser: /assets/images/teasers/default.svg
enable_copy_code_button: true

markdown: kramdown
theme: minimal-mistakes-jekyll

permalink: pretty
timezone: Canada/Mountain

pagination:
  enabled: true

exclude:
  - node_modules
  - scripts
  - package.json
  - package-lock.json

include:
  - _pages

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-cache-bust
  - jekyll-mentions

author:
  name: Trevor Lauder
  avatar: /assets/images/authorimage.webp
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/trevorlauder
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/trevor-lauder

social:
  links:
    - https://github.com/trevorlauder
    - https://www.linkedin.com/in/trevor-lauder

footer:
  since: 2021
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/trevorlauder
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/trevor-lauder

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      related: true
      show_date: true
      classes: wide
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: giscus
  giscus:
    repo: trevorlauder/trevorlauder.dev
    repo_id: R_kgDOPfJXCw
    category_name: Announcements
    category_id: DIC_kwDOPfJXC84CuQOr
    discussion_term: pathname
    reactions_enabled: 1
    strict: 1
    theme: https://trevorlauder.dev/assets/css/giscus-dark.css
