name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
      - uses: actions/setup-node@v6
        with:
          node-version: "24.10.0"
          cache: "npm"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-
      - run: npm ci
      - uses: pre-commit/action@v3.0.1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "24.10.0"
          cache: "npm"
      - run: npm ci
      - run: npm run build
